package com.cater.tos.beans;
// Generated Dec 24, 2015 12:22:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AddressDetails generated by hbm2java
 */
public class AddressDetails  implements java.io.Serializable {


     private Long id;
     private MasterCity masterCity;
     private String line1;
     private String line2;
     private String line3;
     private String pincode;
     private boolean isDeleted;
     private Set catererAddresses = new HashSet(0);

    public AddressDetails() {
    }

	
    public AddressDetails(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public AddressDetails(MasterCity masterCity, String line1, String line2, String line3, String pincode, boolean isDeleted, Set catererAddresses) {
       this.masterCity = masterCity;
       this.line1 = line1;
       this.line2 = line2;
       this.line3 = line3;
       this.pincode = pincode;
       this.isDeleted = isDeleted;
       this.catererAddresses = catererAddresses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public MasterCity getMasterCity() {
        return this.masterCity;
    }
    
    public void setMasterCity(MasterCity masterCity) {
        this.masterCity = masterCity;
    }
    public String getLine1() {
        return this.line1;
    }
    
    public void setLine1(String line1) {
        this.line1 = line1;
    }
    public String getLine2() {
        return this.line2;
    }
    
    public void setLine2(String line2) {
        this.line2 = line2;
    }
    public String getLine3() {
        return this.line3;
    }
    
    public void setLine3(String line3) {
        this.line3 = line3;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Set getCatererAddresses() {
        return this.catererAddresses;
    }
    
    public void setCatererAddresses(Set catererAddresses) {
        this.catererAddresses = catererAddresses;
    }




}


