package com.cater.tos.beans;
// Generated Dec 24, 2015 12:22:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.springframework.util.AutoPopulatingList;

/**
 * Caterer generated by hbm2java
 */
public class Caterer  implements java.io.Serializable {


     private Long catererId;
     private String displayName;
     private String name;
     private String ownerName;
     private boolean isDeleted;
     private String username;
     private String password;
     private List<CatererLineContact> catererLineContacts=new AutoPopulatingList<>(CatererLineContact.class);
     private List<CatererAddress> catererAddresses=new AutoPopulatingList<>(CatererAddress.class);

    public Caterer() {
    }

	
    public Caterer(boolean isDeleted, String username, String password) {
        this.isDeleted = isDeleted;
        this.username = username;
        this.password = password;
    }
   
    public Long getCatererId() {
        return this.catererId;
    }
    
    public void setCatererId(Long catererId) {
        this.catererId = catererId;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOwnerName() {
        return this.ownerName;
    }
    
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }


	public List<CatererLineContact> getCatererLineContacts() {
		return catererLineContacts;
	}


	public void setCatererLineContacts(List<CatererLineContact> catererLineContacts) {
		this.catererLineContacts = catererLineContacts;
	}


	public List<CatererAddress> getCatererAddresses() {
		return catererAddresses;
	}


	public void setCatererAddresses(List<CatererAddress> catererAddresses) {
		this.catererAddresses = catererAddresses;
	}





}


