package com.cater.tos.beans;
// Generated Dec 24, 2015 12:22:57 AM by Hibernate Tools 4.3.1



/**
 * CaterDb generated by hbm2java
 */
public class CaterDb  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private float lat;
     private float lng;
     private String email;
     private int phone;

    public CaterDb() {
    }

    public CaterDb(String name, String address, float lat, float lng, String email, int phone) {
       this.name = name;
       this.address = address;
       this.lat = lat;
       this.lng = lng;
       this.email = email;
       this.phone = phone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public float getLat() {
        return this.lat;
    }
    
    public void setLat(float lat) {
        this.lat = lat;
    }
    public float getLng() {
        return this.lng;
    }
    
    public void setLng(float lng) {
        this.lng = lng;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }




}


