package com.cater.tos.beans;
// Generated Dec 24, 2015 12:22:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MasterState generated by hbm2java
 */
public class MasterState  implements java.io.Serializable {


     private Long stateId;
     private MasterCountry masterCountry;
     private String stateName;
     private boolean visible;
     private Set masterCities = new HashSet(0);

    public MasterState() {
    }

	
    public MasterState(String stateName, boolean visible) {
        this.stateName = stateName;
        this.visible = visible;
    }
    public MasterState(MasterCountry masterCountry, String stateName, boolean visible, Set masterCities) {
       this.masterCountry = masterCountry;
       this.stateName = stateName;
       this.visible = visible;
       this.masterCities = masterCities;
    }
   
    public Long getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Long stateId) {
        this.stateId = stateId;
    }
    public MasterCountry getMasterCountry() {
        return this.masterCountry;
    }
    
    public void setMasterCountry(MasterCountry masterCountry) {
        this.masterCountry = masterCountry;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public Set getMasterCities() {
        return this.masterCities;
    }
    
    public void setMasterCities(Set masterCities) {
        this.masterCities = masterCities;
    }




}


