package com.cater.dto.beans;
// Generated Dec 24, 2015 12:22:57 AM by Hibernate Tools 4.3.1



/**
 * CatererAddress generated by hbm2java
 */
public class CatererAddress  implements java.io.Serializable {


     private Long id;
     private AddressDetails addressDetails;
     private Caterer caterer;
     private boolean isDeleted;
     private String lat;
     private String lng;

    public CatererAddress() {
    }

    /**
	 * @param id
	 * @param addressDetails
	 * @param caterer
	 * @param isDeleted
	 * @param lat
	 * @param lng
	 */
	public CatererAddress(Long id, AddressDetails addressDetails, Caterer caterer, boolean isDeleted, String lat,
			String lng) {
		super();
		this.id = id;
		this.addressDetails = addressDetails;
		this.caterer = caterer;
		this.isDeleted = isDeleted;
		this.lat = lat;
		this.lng = lng;
	}

	public String getLat() {
		return lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getLng() {
		return lng;
	}

	public void setLng(String lng) {
		this.lng = lng;
	}

	public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public AddressDetails getAddressDetails() {
        return this.addressDetails;
    }
    
    public void setAddressDetails(AddressDetails addressDetails) {
        this.addressDetails = addressDetails;
    }
    public Caterer getCaterer() {
        return this.caterer;
    }
    
    public void setCaterer(Caterer caterer) {
        this.caterer = caterer;
    }
    public boolean isIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }




}


