package com.cater.dto.beans;
// Generated Dec 24, 2015 12:22:57 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MasterCity generated by hbm2java
 */
public class MasterCity  implements java.io.Serializable {


     private Long cityId;
     private MasterState masterState;
     private String cityName;
     private boolean visible;
     private Set addressDetailses = new HashSet(0);

    public MasterCity() {
    }

	
    public MasterCity(String cityName, boolean visible) {
        this.cityName = cityName;
        this.visible = visible;
    }
    public MasterCity(MasterState masterState, String cityName, boolean visible, Set addressDetailses) {
       this.masterState = masterState;
       this.cityName = cityName;
       this.visible = visible;
       this.addressDetailses = addressDetailses;
    }
   
    public Long getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }
    public MasterState getMasterState() {
        return this.masterState;
    }
    
    public void setMasterState(MasterState masterState) {
        this.masterState = masterState;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public boolean isVisible() {
        return this.visible;
    }
    
    public void setVisible(boolean visible) {
        this.visible = visible;
    }
    public Set getAddressDetailses() {
        return this.addressDetailses;
    }
    
    public void setAddressDetailses(Set addressDetailses) {
        this.addressDetailses = addressDetailses;
    }




}


